# -*- coding: utf-8 -*-
"""GDP and Life Expectation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S9EkpuUr2E58vggIRRIdyjLvKdqRI0s9

#🟣 1. Título: **🌍 Global Development Analysis: GDP and Life Expectation**

##🟣 2. Objetivo

The objective of this analysis is to explore relationships between economic development (GDP) and life expectation across different regions, identifying patterns and potential insights.

##🟣 3. Carga de datos

Se utiliza el dataset público de la página https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv
"""

#Importar librerías
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#Carga de Datos
url = "https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv"
df = pd.read_csv(url)
df.head()

"""##🟣 4. Limpieza de datos"""

#Limpieza de Datos:
df.info()
df.describe()

# Ejemplo limpieza
df = df.dropna()

#Data was cleaned by removing missing values to ensure consistency.

"""*Data was cleaned by removing missing values to ensure consistency.*

##🟣 5. Exploración inicial (EDA)
"""

df['continent'].value_counts()
df.groupby('continent')['gdpPercap'].mean()

"""##🟣 6. Visualizaciones"""

sns.boxplot(x='continent', y='gdpPercap', data=df)
plt.xticks(rotation=45)
plt.show()
sns.scatterplot(x='gdpPercap', y='lifeExp', hue='continent', data=df)
plt.show()

df[['gdpPercap', 'lifeExp']].corr()
sns.lmplot(x='gdpPercap', y='lifeExp', data=df)

"""↗  *There is a positive correlation between GDP and life expectancy*

##🟣 7. Insights

- Countries with higher GDP per capita tend to have higher life expectancy
- Africa shows lower GDP and lower life expectancy compared to other regions
- Europe and Americas present higher development indicators

##🟣 8. Conclusion

This analysis shows a clear relationship between economic development and life expectancy. Higher GDP per capita is generally associated with better living conditions and longer life expectancy, highlighting global inequalities between regions.
"""