# -*- coding: utf-8 -*-
"""🇦🇷 Argentina Trade Balance Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yk3Q-VohRtne4KksnYZKwOeDGvFQTHex

#🟣 1. Título - 🇦🇷 **Argentina's Trade Balance Analysis: Exports vs Imports**

##🟣 2. Objetivo

El objetivo de este análisis es explorar la evolución de la **Balanza Comercial de Argentina**, comparando Exportaciones e Importaciones a lo largo del tiempo además de identificar tendencias claves y desequilibrios.

*The objective of this analysis is to explore Argentina’s trade balance evolution, comparing Exports and Imports over time and identifying key trends and imbalances.*

##🟣 3. Carga de datos
"""

"""
🇦🇷 Argentina Trade Balance Analysis
=====================================
Datos reales tomados de la fueb World Bank Open Data API.
Indicadores utilizados
  - NE.EXP.GNFS.CD  → Exports of goods and services (USD)
  - NE.IMP.GNFS.CD  → Imports of goods and services (USD)
  - NY.GDP.MKTP.CD  → GDP (USD)

World Bank API docs: https://datahelpdesk.worldbank.org/knowledgebase/articles/889392
"""

# ── Librerías ────────────────────────────────────────────────────────────────
# requests: para llamar a la API del World Bank directamente desde Python.
# No se descarga ningún archivo manualmente.
import requests
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.patches as mpatches

# Estilo global
import matplotlib as mpl
mpl.rcParams.update({
    "figure.dpi": 150,
    "axes.titlesize": 13,
    "axes.titleweight": "bold",
    "axes.labelsize": 11,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": True,
    "grid.alpha": 0.4,
    "grid.linestyle": "--",
})


# ── Función para llamar a la API del World Bank ──────────────────────────────

def fetch_worldbank(indicator: str, country: str = "AR",
                    start: int = 1990, end: int = 2023) -> pd.Series:
    """
    Descarga una serie anual del World Bank para un país dado.
    Retorna un pd.Series con índice de año (int) y valores en USD.
    """
    url = (
        f"https://api.worldbank.org/v2/country/{country}"
        f"/indicator/{indicator}"
        f"?format=json&per_page=100&date={start}:{end}"
    )
    response = requests.get(url, timeout=15)
    response.raise_for_status()          # Da error si la API falla
    payload = response.json()

    # El World Bank devuelve una lista de dos elementos: [metadata, datos]
    records = payload[1]
    series = {
        int(r["date"]): r["value"]
        for r in records
        if r["value"] is not None      # excluir años sin dato
    }
    return pd.Series(series, name=indicator).sort_index()

    # ── Descarga de datos reales ─────────────────────────────────────────────────
print("Descargando datos del World Bank...")

exports = fetch_worldbank("NE.EXP.GNFS.CD")
imports = fetch_worldbank("NE.IMP.GNFS.CD")
gdp     = fetch_worldbank("NY.GDP.MKTP.CD")

print(f"  Exports:  {len(exports)} años ({exports.index.min()}–{exports.index.max()})")
print(f"  Imports:  {len(imports)} años ({imports.index.min()}–{imports.index.max()})")
print(f"  GDP:      {len(gdp)} años ({gdp.index.min()}–{gdp.index.max()})")

"""##🟣 4. Data Preparation"""

# Convertir a miles de millones

df = pd.DataFrame({
    "exports": exports,
    "imports": imports,
    "gdp":     gdp,
}).dropna()

df["trade_balance"] = df["exports"] - df["imports"]
df["exports_bn"] = df["exports"] / 1e9
df["imports_bn"] = df["imports"] / 1e9
df["trade_balance_bn"] = df["trade_balance"] / 1e9
df["openness"] = (df["exports"] + df["imports"]) / df["gdp"] * 100

print(f"\nDataset final: {len(df)} años ({df.index.min()}–{df.index.max()})")
print(f"Valores faltantes: {df.isnull().sum().sum()}")

"""##🟣 5. Análisis Exportaciones vs. Importaciones📊"""

fig, ax = plt.subplots(figsize=(11, 5))

ax.fill_between(df.index, df["exports_bn"], df["imports_bn"],
                where=df["exports_bn"] >= df["imports_bn"],
                alpha=0.25, color="#2ca02c", label="_surplus_fill")

ax.fill_between(df.index, df["exports_bn"], df["imports_bn"],
                where=df["exports_bn"] < df["imports_bn"],
                alpha=0.25, color="#d62728", label="_deficit_fill")

ax.plot(df.index, df["exports_bn"], color="#2ca02c",
        linewidth=2, marker="o", markersize=4, label="Exports")
ax.plot(df.index, df["imports_bn"], color="#d62728",
        linewidth=2, marker="o", markersize=4, label="Imports")

# Años con eventos macroeconómicos claves
events = {2001: "Crisis\n2001", 2009: "Global\ncrisis", 2020: "COVID-19"}
for year, label in events.items():
    if year in df.index:
        ax.axvline(year, color="gray", linestyle=":", linewidth=1, alpha=0.7)
        ax.text(year + 0.2, df["exports_bn"].max() * 0.95, label,
                fontsize=8, color="gray", va="top")

ax.set_title("Argentina: Exports vs. Imports of goods & services\n"
             "Source: World Bank (NE.EXP.GNFS.CD, NE.IMP.GNFS.CD)", pad=12)
ax.set_xlabel("Year")
ax.set_ylabel("USD (billions)")
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x:.0f}B"))
ax.set_xticks(df.index[::2])
ax.tick_params(axis="x", rotation=45)

surplus_patch = mpatches.Patch(color="#2ca02c", alpha=0.3, label="Trade surplus")
deficit_patch = mpatches.Patch(color="#d62728", alpha=0.3, label="Trade deficit")
ax.legend(handles=[*ax.get_legend_handles_labels()[0][:2], surplus_patch, deficit_patch],
          fontsize=9, loc="upper left")

plt.tight_layout()
plt.savefig("01_exports_vs_imports.png", dpi=150, bbox_inches="tight")
plt.show()

"""*This chart shows the evolution of exports and imports over time, allowing a direct comparison of trade dynamics.*

##🟣 6. Análisis Balanza Comercial📊
"""

fig, ax = plt.subplots(figsize=(11, 4))

colors = ["#2ca02c" if v >= 0 else "#d62728" for v in df["trade_balance_bn"]]
ax.bar(df.index, df["trade_balance_bn"], color=colors, alpha=0.8, width=0.7)
ax.axhline(0, color="black", linewidth=0.8, linestyle="-")

ax.set_title("Argentina: Trade balance (Exports − Imports)\n"
             "Green = surplus  ·  Red = deficit", pad=12)
ax.set_xlabel("Year")
ax.set_ylabel("USD (billions)")
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x:.0f}B"))
ax.set_xticks(df.index[::2])
ax.tick_params(axis="x", rotation=45)

plt.tight_layout()
plt.savefig("02_trade_balance.png", dpi=150, bbox_inches="tight")
plt.show()

"""##🟣 7. Apertura comercial como % del PBI"""

fig, ax = plt.subplots(figsize=(11, 4))

ax.plot(df.index, df["openness"], color="#1f77b4",
        linewidth=2, marker="o", markersize=4)
ax.fill_between(df.index, df["openness"], alpha=0.15, color="#1f77b4")

ax.set_title("Argentina: Trade openness (Exports + Imports as % of GDP)\n"
             "Source: World Bank", pad=12)
ax.set_xlabel("Year")
ax.set_ylabel("% of GDP")
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{x:.0f}%"))
ax.set_xticks(df.index[::2])
ax.tick_params(axis="x", rotation=45)

plt.tight_layout()
plt.savefig("03_trade_openness.png", dpi=150, bbox_inches="tight")
plt.show()

best_year  = df["trade_balance_bn"].idxmax()
worst_year = df["trade_balance_bn"].idxmin()
best_val   = df.loc[best_year,  "trade_balance_bn"]
worst_val  = df.loc[worst_year, "trade_balance_bn"]
avg_open   = df["openness"].mean()
surplus_yrs = (df["trade_balance_bn"] >= 0).sum()
deficit_yrs = (df["trade_balance_bn"] <  0).sum()

print("\n=== KEY INSIGHTS ===")
print(f"Best trade surplus:   {best_year}  → ${best_val:.1f}B")
print(f"Worst trade deficit:  {worst_year} → ${worst_val:.1f}B")
print(f"Average trade openness (1990–2023): {avg_open:.1f}% of GDP")
print(f"Years in surplus: {surplus_yrs}  |  Years in deficit: {deficit_yrs}")

"""## 🟣 8. Insights

*   Argentina shows alternating periods of trade surplus and deficit across the analyzed years.
*   Imports appear to be more volatile than exports, suggesting sensitivity to economic conditions.
*   A significant drop in imports can be observed in 2020, which may be associated with economic restrictions or reduced domestic demand.
*   Post-2020, exports increase notably, contributing to a stronger trade balance.
*   Variations in imports could be influenced by exchange rate dynamics and trade regulations.

##🟣 9. Conclusión

La balanza comercial de Argentina muestra una marcada ciclicidad a lo largo de tres décadas. Los mayores superávits coinciden con períodos de fuerte demanda de exportaciones (2002–2009), mientras que los déficits más pronunciados se asocian a etapas de mayor apertura importadora y presión sobre el tipo de cambio. La apertura comercial alcanzó su pico a principios de los 2000, evidenciando la estrecha relación entre la política cambiaria y la dinámica del comercio exterior. Estos patrones reflejan la complejidad operativa inherente a la gestión de pagos internacionales y el cumplimiento normativo en entornos de alta volatilidad macroeconómica.

*Argentina's trade balance shows marked cyclicality over three decades. The strongest surpluses coincide with periods of strong export demand (2002–2009), while the most pronounced deficits are associated with phases of higher import openness and exchange rate pressure. Trade openness peaked in the early 2000s, reflecting the close relationship between exchange rate policy and trade dynamics. These patterns illustrate the operational complexity inherent in managing international payments and regulatory compliance in high macroeconomic volatility environments.*
"""