# -*- coding: utf-8 -*-
"""Simulation: 🇦🇷 Argentina Trade Balance Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sm7f5DV9BSqsHtXF6mnC3yT4KrSE7O4Y

#🟣 1. Título: 🇦🇷 **Argentina's Trade Balance Analysis: Exports vs Imports**

##🟣 2. Objetivo

The objective of this analysis is to explore Argentina’s trade balance evolution, comparing Exports and Imports over time and identifying key trends and imbalances.

##🟣 3. Carga de datos
"""

import pandas as pd
import matplotlib.pyplot as plt

data = {
    'Year': [2015,2016,2017,2018,2019,2020,2021,2022],
    'Exports': [60000,58000,62000,65000,61000,54000,77000,88000],
    'Imports': [59000,55000,66000,70000,65000,42000,63000,81000]
}

df_year = pd.DataFrame(data)
df_year

"""*A simplified dataset was created to simulate Argentina’s trade balance dynamics for analytical purposes.*

###Balanza Comercial
"""

df_year['Trade_Balance'] = df_year['Exports'] - df_year['Imports']
df_year

"""##🟣 8. Visualizations📊"""

df_year.plot(x='Year', y=['Exports','Imports'], figsize=(10,5))
plt.title("Argentina: Exports vs Imports")
plt.ylabel("USD (millions)")
plt.show()

"""*This chart shows the evolution of exports and imports over time, allowing a direct comparison of trade dynamics.*"""

df_year.plot(x='Year', y='Trade_Balance', figsize=(10,5))
plt.axhline(0, color='red', linestyle='--')
plt.title("Argentina: Trade Balance")
plt.ylabel("USD (millions)")
plt.show()

"""*The red line represents the equilibrium point. Values above indicate trade surplus, while values below indicate trade deficit.*

## 🟣 9. Insights

*   Argentina shows alternating periods of trade surplus and deficit across the analyzed years.
*   Imports appear to be more volatile than exports, suggesting sensitivity to economic conditions.
*   A significant drop in imports can be observed in 2020, which may be associated with economic restrictions or reduced domestic demand.
*   Post-2020, exports increase notably, contributing to a stronger trade balance.
*   Variations in imports could be influenced by exchange rate dynamics and trade regulations.

##🟣 10. Conclusión

The analysis highlights the cyclical nature of Argentina’s trade balance, influenced by economic conditions and external factors. Managing the balance between imports and exports is key to maintaining economic stability.
"""