# -*- coding: utf-8 -*-
"""Transactions - Detecting Patterns and Anomalies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eezI3ML_m00XSCoPBDVbG08RFoMR7r7l

#🟣 1. Title: **💳 Transaction Analysis: Patterns and Anomaly Detection**

##🟣 2. Objective

The objective of this analysis is to explore transaction patterns and identify potential anomalies based on transaction amounts.

##🟣 3. Dataset
"""

import pandas as pd
import numpy as np

np.random.seed(42)
data = {
    'Transaction_ID': range(1,101),
    'Amount': np.random.normal(500, 150, 100),
    'Type': np.random.choice(['Payment','Transfer','Withdrawal'], 100),
    'Country': np.random.choice(['Argentina','Brazil','Chile'], 100)
}

df = pd.DataFrame(data)

# Crear outliers (simulación)
df.loc[[5, 20, 50], 'Amount'] = [2000, 2500, 3000]

df.head()

"""##🟣 4. Data Preparation"""

df.describe()

"""##🟣 5. Analysis"""

df['Amount'].mean()
df['Amount'].std()

"""##🟣 6. Outlier detection"""

threshold = df['Amount'].mean() + 2*df['Amount'].std()
df['Anomaly'] = df['Amount'] > threshold

"""##🟣 7. Visualizations"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x=df['Amount'])
plt.show()

sns.scatterplot(x=df.index, y='Amount', hue='Anomaly', data=df)
plt.show()

"""##🟣 8. Insights

* Most transactions fall within a normal range
* A few transactions significantly exceed the average
* These anomalies could indicate unusual activity or potential risk

##🟣 9. Conclusion

Identifying anomalies in transaction data is key for risk management and fraud detection, supporting better financial decision-making.
"""